export const NATIONALITY = {
    AU:'AU',
    BR:'BR',
    CA:'CA',
    CH: 'CH',
    DE: 'DE',
    DK: 'DK',
    ES: 'ES',
    FI: 'FI',
    FR: 'FR',
    GB: 'GB',
    IE: 'IE',
    IR: 'IR',
    NO: 'NO',
    NL: 'NL',
    NZ: 'NZ',
    TR: 'TR',
    US: 'US'
};

export const NATIONALITY_HUMAN_NAME = {
    [NATIONALITY.AU]: 'Australia',
    [NATIONALITY.BR]: 'Brazil',
    [NATIONALITY.CA]: 'Canada',
    [NATIONALITY.CH]: 'Chines',
    [NATIONALITY.DE]: 'Germany',
    [NATIONALITY.DK]: 'Denmark',
    [NATIONALITY.ES]: 'Spain',
    [NATIONALITY.FI]: 'Finland',
    [NATIONALITY.FR]: 'France',
    [NATIONALITY.GB]: 'United Kingdom',
    [NATIONALITY.IE]: 'Ireland',
    [NATIONALITY.IR]: 'Iran',
    [NATIONALITY.NO]: 'Norway',
    [NATIONALITY.NL]: 'Netherlands',
    [NATIONALITY.NZ]: 'New Zealand',
    [NATIONALITY.TR]: 'Turkey',
    [NATIONALITY.US]: 'United States of America',
};